'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class enationdemo
    Public Property id As String
    Public Property createdAt As System.DateTimeOffset
    Public Property updatedAt As Nullable(Of System.DateTimeOffset)
    Public Property version As Byte()
    Public Property deleted As Nullable(Of Boolean)
    Public Property Name As String
    Public Property EmailId As String
    Public Property Age As Nullable(Of Double)
    Public Property Gender As String

End Class
